spring:
    application:
        name: auth
    output:
        ansi:
            enabled: always
    config:
        import: optional:file:.env[.properties]
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
jwt:
    #secret: ${JWT_SECRET}
    secret: miSecretKeydebetenerporlomenostreintaydoscaracteres
    expirationTimeMinutes: 60