spring:
    application:
        name: auth
    output:
        ansi:
            enabled: always
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DB_URI}
        username: ${DB_USER}
        password: ${DB_PASS}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
    secret: ${JWT_SECRET}
    expirationTimeMinutes: 60