server:
    address: 0.0.0.0
    port: 8080
spring:
    application:
        name: auth
    output:
        ansi:
            enabled: always
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_EXTRA_PARAMS}
        username: ${DB_USER}
        password: ${DB_PASS}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create-drop
            #ddl-auto: update
        show-sql: false
    security:
        user:
            password:
logging:
    level:
        root: INFO
        '[com.prtec]': DEBUG
        '[org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator]': ERROR
        '[org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer"]': ERROR
custom:
    database:
        name: ${DB_NAME}
    security:
        jwt:
            secret: ${JWT_SECRET}
            expiration-time-minutes: 60
        cors:
            allowed-origins: >
                http://localhost:4200,
                http://localhost,
                http://host.docker.internal
            allowed-methods: >
                GET,
                POST,
                PUT,
                DELETE,
                OPTIONS
            allowed-headers: >
                Authorization,
                Content-Type,
                Accept
        public-paths: >
            /api/register,
            /api/login,
            /api/verify,
            /v2/api-docs/**,
            /v3/api-docs/**,
            /swagger-resources/**,
            /swagger-ui/**,
            /webjars/**